### PR TITLE
Next/Previous Pokemon buttons

### PR DESCRIPTION
**Pull request by CypherX**
Adds buttons to the pokemon page to go to the next or previous pokemon.

image
image

### CODE REVIEW

**Comment by wormania** [comment]
Nice, something I can cross off my todo list. What are your thoughts about only cycling through Pokedex numbers and showing the alt forms on the page instead, I was playing around with this:
image

**Comment by CypherX** [comment]
> Nice, something I can cross off my todo list. What are your thoughts about only cycling through Pokedex numbers and showing the alt forms on the page instead, I was playing around with this: image

Seems like a good idea to me. Will need to be careful with how the alt forms are displayed because of things like Alcremie and Magikarp. Pant is the one who mentioned this Next/Previous thing to me yesterday so let's also see what they have to say.

**Comment by EatPant2nd** [comment]
I would rather Alternate Forms get its own page like in Miraheze. Too much information in an individual page.

**Comment by EatPant2nd** [comment]
Anyway, considering some of those alternate forms can be regional forms, it would be a bit problematic to skip, not mentioning that some would be weird like Unown (A) jumping to whatever is next and ignoring the other Unown, for example. Like this it's fine as it helps with going to previous / next page.

Thanks for the PR.

**Pull request merged**
