### PR TITLE
Added details for Generation I Berries.

### PR DESCRIPTION
**Pull request by UnicornSnuggler**

### CODE REVIEW

**Comment by UnicornSnuggler** [comment]
I stopped here because it was a good stopping point...but also because we really need to devise a better methodology for displaying the mutation charts. The existing chart on the `Jaboca` page is...really unappetizing to look at and honestly kind of hard to read. There has to be a better way.

**Comment by RedSparr0w** [comment]
Thanks for the PR! 👍 
You can submit changes to any page straight from the wiki now, just sign in up the top right and edit away.

The pages take a few minutes to update though, so just be aware of that.

**Comment by RedSparr0w** [comment]
Definitely agree the mutation tables need some work though, not really sure the best way to go about it tbh.

**Comment by RedSparr0w** [comment]
Added some more markdown to support smaller tables:
```md
::: table-tight

table here

:::
```
image

```md
::: table-auto

table here

:::
```
image

**Pull request merged**
